all:
  children:
    network_hosts:
      hosts:
        a: null
  hosts:
    a:
      ansible_connection: ansible.netcommon.network_cli
      ansible_host: 172.16.99.196
      ansible_network_os: cisco.ios.ios
      ansible_password: coscp
      ansible_port: 5022
      ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
      ansible_ssh_pass: coscp
      ansible_user: admin
